const t = require('@babel/types');
const fs = require('fs');
const path = require('path');

/**
 * Synchronizes Babel node types with ml/constants.py to ensure the ML model
 * always has the same vocabulary as the parser.
 */

const CUSTOM_TYPES = ["Builtin_require", "Builtin_defineProperty", "Builtin_exports", "Builtin_module"];
const BASE_TYPES = ["PAD", "UNKNOWN"];

// Get all Babel types and sort them for stability
const babelTypes = t.TYPES.filter(type => !BASE_TYPES.includes(type) && !CUSTOM_TYPES.includes(type)).sort();

const allTypes = [...BASE_TYPES, ...babelTypes, ...CUSTOM_TYPES];

const constantsContent = `# Generated by src/sync_vocab.js
# Do not edit manually. Run 'npm run sync-vocab' to update.

NODE_TYPES = [
${allTypes.map(type => `    "${type}"`).join(',\n')}
]

TYPE_TO_ID = {t: i for i, t in enumerate(NODE_TYPES)}
VOCAB_SIZE = len(NODE_TYPES) + 100

# Model configuration
MAX_NODES = 2048 # Safer default for Transformers. Use --batch_size 1 for 4096 on limited VRAM.
MAX_LITERALS = 32
`;

const targetPath = path.join(__dirname, '../ml/constants.py');
fs.writeFileSync(targetPath, constantsContent);
console.log(`[*] Successfully synchronized ${allTypes.length} node types to ${targetPath}`);
